name: mindful_flutter_themes
description: A set of Material 3 themes.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  dynamic_color: ^1.6.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mindful_analysis: ^1.0.0+2
